#===============================================================================
# 全体の設定
#===============================================================================

# prefix を C-] に変更
set -g prefix C-]

# prefix + C-r で .tmux.conf をリロード
bind C-r source-file ~/.tmux.conf

# tmux 内のターミナルタイプを 256 色に対応
set -g default-terminal "xterm-256color"

# その上で、True Color（e.g. #abcdef）も有効化
set -ga terminal-overrides ',xterm-256color:Tc'

#===============================================================================
# ステータスバーの設定
#===============================================================================

# 更新間隔
set -g status-interval 10

# 背景色
set -g status-style bg=colour166

# 使用中のウィンドウの色
setw -g window-status-current-style bg=black,fg=white

#===============================================================================
# ウィンドウ＆ペインの設定
#===============================================================================

# Space キーで次のウィンドウへ
bind " " next-window

# ウィンドウを横に分割
bind 2 split-window -h

# ウィンドウを縦横に分割（上 1 ペイン小、下 2 ペイン）
bind 3 split-window -v \; select-pane -t 0 \; resize-pane -y 20 \; select-pane -D \; split-window -h

# ウィンドウを縦と横に分割（4 ペイン）
bind 4 split-window -v \; split-window -h \; select-pane -t 0 \; split-window -h \; select-pane -t 0

# ペインをウィンドウとして分離
bind 1 break-pane

# prefix + k でウィンドウを kill
bind k kill-window

# prefix + C-k でペインを kill
bind C-k kill-pane
